python1812AXF/python1812AXF/axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns = [
    #主页面
    url(r'^$',views.home,name='home'),
    #商品页
    url(r'^market/$',views.market,name='marketbase'),#闪购超市
url(r'^market/(?P<childcid>\d+)/(?P<sortid>\d+)/$',views.market,name='market'),#闪购超市
    #购物车
    url(r'^cart/$',views.cart,name='cart'),
    #我的
    url(r'^mine/$',views.mine,name='mine'),
    #登录
    url(r'^login/$',views.login,name='login'),
    #退出
    url(r'^loginout/$', views.logout, name='logout'),
    #注册
    url(r'^register/$', views.register, name='register'),


    #账号验证
    url(r'^checkemail/$',views.checkemail,name='checkemail'),

    #加操作
    url(r'^addcart/$',views.addcart,name='addcart'),
    #减操作
    url(r'^subcart/$',views.subcart,name='subcart'),

    #修改商品选中状态
    url(r'^changecarrtselect/$',views.changecarrtselect,name='changecarrtselect'),

    #全选/取消全选
    url(r'^changecartall/$', views.changecartall, name='changecartall'),
    #生成订单
    url(r'^generateorder/$',views.generateorder,name='generateorder'),
    # 订单列表
    url(r'orderlist/$', views.orderlist, name='orderlist'),
    # 订单详情
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail, name='orderdetail'),


    # 测试接口
    url(r'^randomtest/$', views.randomtest, name='randomtest'),
    # 支付成功后，客户端的显示
    url(r'^returnurl/$', views.returnurl, name='returnurl'),
    # 支付成功后，订单的处理
    url(r'^appnotifyurl/$', views.appnotifyurl, name='appnotifyurl'),
    # 支付
    url(r'^pay/$', views.pay, name='pay'),
]

python1812AXF/python1812AXF/python1812AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^axf/',include('axf.urls',namespace='axf')),
]

python1812AXF/python1812AXF/templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}

{#　标题　#}
{% block title %}
    首页
{% endblock %}


{#　css　#}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}


{# 头部 #}
{% block header %}
    购物车
{% endblock %}


{#　主体内容　#}
{% block content %}
    <div class="cart">
        <ul>
            {% for cart in carts %}
                <li>
                    <div class="confirm-wrapper" data-cardid="{{ cart.id }}">
                        {% if cart.isselect %}
                            <span class="glyphicon glyphicon-ok"></span>
                        {% else %}
                            <span class="no"></span>
                        {% endif %}
                    </div>

                    <div class="content-wrapper">
                        <div class="img">
                            <img src="{{ cart.goods.productimg }}" alt="">
                        </div>
                        <div class="detail">
                            <p class="name" data-nume>{{ cart.goods.productlongname }}</p>
                            <p class="price" data-price="{{ cart.goods.price }}">{{ cart.goods.price }}</p>
                            <p class="num" data-number="{{ cart.number }}">X{{ cart.number }}</p>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>


        <div class="bill">
            <div class="bill-left">
                <div class="all" isall="false">
                    <span class="no"></span>
                    <b>全选</b>
                </div>
                <div class="total">
                    <span>￥</span>
                    <b></b>

                </div>
            </div>

            <div class="bill-right">
                <a href="{% url 'axf:generateorder' %}">下单</a>
            </div>
        </div>
    </div>


{% endblock %}


{# 底部 #}
{#{% block footer %}#}
{#{% endblock %}#}

{#　ｊｓ　#}
{% block extjs %}
    <script src="{% static 'cart/js/cart.js' %}"></script>
{% endblock %}

python1812AXF/python1812AXF/templates/cart/on-login.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="no-login">
        <a href="{% url 'axf:login' %}">
            请登录后操作
        </a>
    </div>
{% endblock %}