python1812AXF/python1812AXF/axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns = [
    #主页面
    url(r'^$',views.home,name='home'),
    #商品页
    url(r'^market/$',views.market,name='marketbase'),#闪购超市
url(r'^market/(?P<childcid>\d+)/(?P<sortid>\d+)/$',views.market,name='market'),#闪购超市
    #购物车
    url(r'^cart/$',views.cart,name='cart'),
    #我的
    url(r'^mine/$',views.mine,name='mine'),
    #登录
    url(r'^login/$',views.login,name='login'),
    #退出
    url(r'^loginout/$', views.logout, name='logout'),
    #注册
    url(r'^register/$', views.register, name='register'),


    #账号验证
    url(r'^checkemail/$',views.checkemail,name='checkemail'),

    #加操作
    url(r'^addcart/$',views.addcart,name='addcart'),
    #减操作
    url(r'^subcart/$',views.subcart,name='subcart'),

    #修改商品选中状态
    url(r'^changecarrtselect/$',views.changecarrtselect,name='changecarrtselect'),

    #全选/取消全选
    url(r'^changecartall/$', views.changecartall, name='changecartall'),
    #生成订单
    url(r'^generateorder/$',views.generateorder,name='generateorder'),
    # 订单列表
    url(r'orderlist/$', views.orderlist, name='orderlist'),
    # 订单详情
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail, name='orderdetail'),


    # 测试接口
    url(r'^randomtest/$', views.randomtest, name='randomtest'),
    # 支付成功后，客户端的显示
    url(r'^returnurl/$', views.returnurl, name='returnurl'),
    # 支付成功后，订单的处理
    url(r'^appnotifyurl/$', views.appnotifyurl, name='appnotifyurl'),
    # 支付
    url(r'^pay/$', views.pay, name='pay'),
]

python1812AXF/python1812AXF/python1812AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^axf/',include('axf.urls',namespace='axf')),
]

python1812AXF/python1812AXF/templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}

{#　标题　#}
{% block title %}
    注册页
{% endblock %}


{#　css　#}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}


{# 头部 #}
{% block header %}
    爱鲜蜂
{% endblock %}


{#　主体内容　#}
{% block content %}
    <div class="register">
        <form action="{% url 'axf:login' %}" method="post">
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">邮箱</span>
                <input type="text" class="form-control" placeholder="邮箱" aria-describedby="basic-addon1" name="email">
            </div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">密码</span>
                <input type="text" class="form-control" placeholder="密码" aria-describedby="basic-addon1"
                       name="password"></div>
            <input type="submit" value='登录'>
            {% if err_email %}
                <p><span style="color: red">邮箱错误</span></p>
            {% elif err_password %}
                <p><span style="color: red">密码错误</span></p>
            {% endif %}
        </form>
    </div>
{% endblock %}


{# 底部 #}
{% block footer %}
{% endblock %}

{#　ｊｓ　#}
{% block extjs %}
    <script src="{% static 'mine/js/login.js' %}"></script>

{% endblock %}

python1812AXF/python1812AXF/templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    我的
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="mine">
        <div class="user-wrapper">
            <div class="user-img">
                <img src="{% static 'base/img/axf.png' %}" alt="">
            </div>
            <div class="user-content">
                <p>
                    <span class="glyphicon glyphicon-user"></span>
                    <a id="login-i">
                        {{ user.name | default:'未登录' }}
                    </a>
                </p>
                <p>
                    <span class="glyphicon glyphicon-th-list"></span>
                    等级: {{ user.rank | default:'无' }}
                </p>
                <a href="{% url 'axf:register' %}" class="register">注册</a>
            </div>
        </div>

        <div class="collect">
            <span class="glyphicon glyphicon-flash"></span>
            <i>商品收藏</i>
        </div>

        <div class="other">
            <section class="my">
                <span>我的订单</span>
                <a href="{% url 'axf:orderlist' %}">查看全部订单 <i class="glyphicon glyphicon-chevron-right "></i> </a>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl class="item">
                                <dt>
                                    <span class="glyphicon glyphicon-gift"></span>
                                    <span class="badge">{{ waitpay }}</span>
                                </dt>
                                <dd>
                                    待付款
                                </dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="item">
                                    <span class="glyphicon glyphicon-leaf"></span>
                                    <span class="badge">{{ paydone }}</span>
                                </dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-fire"></span></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-plane"></span></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-random"></span></dt>
                                <dd>优惠劵</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-comment"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-magnet"></span></dt>
                                <dd>客户反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-wrench"></span></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            {% if user %}
                <section class="quit">
                    <a href="{% url 'axf:logout' %}">
                        退出
                    </a>
            </section>
            {% endif %}
        </div>
    </div>
{% endblock %}


{#{% extends 'base/base.html' %}#}
{#{% load static %}#}
{##}
{#　标题　#}
{#{% block title %}#}
{#    我的#}
{#{% endblock %}#}
{##}
{##}
{#　css　#}
{#{% block extcss %}#}
{#    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">#}
{#{% endblock %}#}
{##}
{#　ｊｓ　#}
{#{% block extjs %}#}
{#    <script src="{% static 'mine/js/mine.js' %}"></script>#}
{#{% endblock %}#}
{##}
{##}
{# 头部 #}
{#{% block header %}#}
{#    我的#}
{#{% endblock %}#}
{##}
{##}
{#{% block content %}#}
{#    <div class="mine">#}
{#        <div class="user-wrapper">#}
{#            <div class="user-img">#}
{#                <img src="{% static 'base/img/cart1.png' %}" alt="">#}
{#            </div>#}
{#            <div class="user-content">#}
{#                <p>#}
{#                    <span class="glyphicon glyphicon-user"></span>#}
{#                    <a href="{% url 'axf:login' %}">#}
{#                        {{ user.name | default:'未登录' }}#}
{#                    </a>#}
{#                </p>#}
{#                <p>#}
{#                    <span class="glyphicon glyphicon-th-list"></span>#}
{#                    等级: {{ user.rank | default:'无' }}#}
{#                </p>#}
{#                <a href="{% url 'axf:register' %}" class="register">注册</a>#}
{#            </div>#}
{#        </div>#}
{##}
{#        <div class="collect">#}
{#            <span class="glyphicon glyphicon-flash"></span>#}
{#            <i>商品收藏</i>#}
{#        </div>#}
{##}
{#        <div class="other">#}
{#            <section class="my">#}
{#                <span>我的订单</span>#}
{#                <a href="#">查看全部订单 <i class="glyphicon glyphicon-chevron-right "></i> </a>#}
{#            </section>#}
{##}
{#            <section>#}
{#                <ul>#}
{#                    <li>#}
{#                        <a href="#">#}
{#                            <dl>#}
{#                                <dt><span class="glyphicon glyphicon-gift"></span></dt>#}
{#                                <dd>待付款</dd>#}
{#                            </dl>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#">#}
{#                            <dl>#}
{#                                <dt><span class="glyphicon glyphicon-leaf"></span></dt>#}
{#                                <dd>待收货</dd>#}
{#                            </dl>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#">#}
{#                            <dl>#}
{#                                <dt><span class="glyphicon glyphicon-fire"></span></dt>#}
{#                                <dd>待评价</dd>#}
{#                            </dl>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#">#}
{#                            <dl>#}
{#                                <dt><span class="glyphicon glyphicon-plane"></span></dt>#}
{#                                <dd>退款/售后</dd>#}
{#                            </dl>#}
{#                        </a>#}
{#                    </li>#}
{#                </ul>#}
{#            </section>#}
{##}
{#            <section>#}
{#                <ul>#}
{#                    <li>#}
{#                        <a href="#">#}
{#                            <dl>#}
{#                                <dt><span class="glyphicon glyphicon-random"></span></dt>#}
{#                                <dd>优惠劵</dd>#}
{#                            </dl>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#">#}
{#                            <dl>#}
{#                                <dt><span class="glyphicon glyphicon-comment"></span></dt>#}
{#                                <dd>收货地址</dd>#}
{#                            </dl>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#">#}
{#                            <dl>#}
{#                                <dt><span class="glyphicon glyphicon-magnet"></span></dt>#}
{#                                <dd>客户反馈</dd>#}
{#                            </dl>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#">#}
{#                            <dl>#}
{#                                <dt><span class="glyphicon glyphicon-wrench"></span></dt>#}
{#                                <dd>关于我们</dd>#}
{#                            </dl>#}
{#                        </a>#}
{#                    </li>#}
{#                </ul>#}
{#            </section>#}
{##}
{#            {% if user %}#}
{#                <section class="quit">#}
{#                    <a href="{% url 'axf:logout' %}">#}
{#                        退出#}
{#                    </a>#}
{#            </section>#}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}
{##}
{##}
{# 底部 #}
{#{% block footer %}#}
{#{% endblock %}#}

python1812AXF/python1812AXF/templates/mine/register.html
{% extends 'base/base.html' %}
{% load static %}

{#　标题　#}
{% block title %}
    注册页
{% endblock %}


{#　css　#}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}


{# 头部 #}
{% block header %}
    爱鲜蜂
{% endblock %}


{#　主体内容　#}
{% block content %}

    <div class="register">
        <form action="{% url 'axf:register' %}" method="post">
            {#  样式 has-success / has-error     打钩glyphicon-ok / glyphicon-remove     #}
            <div class="input-group" id="email_v">
                <span class="input-group-addon" id="basic-addon1">邮箱</span>
                <input type="text" class="form-control" placeholder="邮箱" aria-describedby="basic-addon1" name="email" id="example" tabindex="0" role="button" data-toggle="popover" data-trigger="focus" title="Dismissible popover" data-content="邮箱格式不正确" data-placement="bottom">
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>
            <br>


            <div class="input-group" id="password_v">
                <span class="input-group-addon" id="basic-addon1">密码</span>
                <input type="text" class="form-control" placeholder="密码6--10位字母数字下划线" aria-describedby="basic-addon1" name="password" id="example_1" tabindex="0" role="button" data-toggle="popover" data-trigger="focus" title="Dismissible popover" data-content="密码格式不正确" data-placement="bottom">
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>
            <br>

            <div class="input-group" id="name_v">
                <span class="input-group-addon" id="basic-addon1">昵称</span>
                <input type="text" class="form-control" placeholder="昵称" aria-describedby="basic-addon1" name="name"
                       id="example_2" tabindex="0" role="button" data-toggle="popover"
                       data-trigger="focus" title="Dismissible popover" data-content="昵称格式不正确" data-placement="bottom">
                 <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>
            <br>
            <input type="file" id="exampleInputFile" name="img">
        </form>
        <input type="button" value="注册" id="register_button">
        <button><a href="{% url 'axf:mine' %}">返回</a></button>
    </div>


    {#</div>#}


{% endblock %}


{# 底部 #}
{% block footer %}
{% endblock %}

{#　ｊｓ　#}
{% block extjs %}
    <script src="{% static 'mine/js/registerr.js' %}"></script>

{% endblock %}